
.binhost-job:
  artifacts:
    expire_in: 7 days
    when: always
    paths:
      - portage
  tags:
    - "gentoo-binhost-$CI_JOB_NAME"
  stage: build
  script:
    - sudo emerge --sync
    # We exclude Qubes OS packages and Gitlab related ones.
    - sudo emerge -uDN @world --quiet-build --buildpkg --buildpkg-exclude "app-emulation/qubes-* */gitlab*"
    - rsync -e "ssh -o StrictHostKeyChecking=no" -av --progress --no-perms --omit-dir-times /var/cache/binpkgs/ "mirror.notset.fr:/data/gentoo/repo/standard/$CI_JOB_NAME/"
  after_script:
    - cp -r /var/log/portage $CI_PROJECT_DIR/

minimal:
  extends: .binhost-job

gnome:
  extends: .binhost-job

xfce:
  extends: .binhost-job
